version: "3.11"
services:
  web:
    init: true
    build: .
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - .:/code
    ports:
      - "8000:5000"

  db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=twitter-metrics
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - HOSTNAME=localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
